config/routes.rb
Rails.application.routes.draw do

  root 'customers#new'

  devise_for :admins

  resources :bookings

  resources :cities

  resources :cleaners do
    get 'confirm_token/:token' => 'cleaners#confirm_token', as: 'confirm_email'
  end

  resources :customers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cleaner
  belongs_to :city
  validates_presence_of :cleaner_id, :city_id, message: "Should be selected"
end

app/models/cities_cleaner.rb
class CitiesCleaner < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :cleaners_cities
  has_many :cleaner, through: :cleaners_cities

  enum status: [:Active, :Inactive]

  validates :name, presence: true
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  has_many :connection1s
  has_many :cleaners, :through => :connection1s, :source => :cleaner

end

app/models/cleaner.rb
class Cleaner < ActiveRecord::Base

  has_many :cleaners_cities, dependent: :destroy
  has_many :booking, dependent: :destroy
  has_many :cities, through: :cleaners_cities

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :quality_score, presence: true

  scope :all_cleaner, -> { ( order(id: :desc) ) }
end

app/models/cleaner_city.rb
class CleanerCity < ActiveRecord::Base

  belongs_to :city
  belongs_to :cleaner

end

app/models/cleaners_city.rb
class CleanersCity < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/connection1.rb
class Connection1 < ActiveRecord::Base
  belongs_to :cleaners, :class_name => "Cleaner"
  belongs_to :connection1s, :class_name => "Connection1"

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :booking, dependent: :destroy

  attr_accessor :city_id, :date

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number,presence: true
  validates :city_id, presence: true
  validates :date, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @bookings = Booking.includes(:cleaner, :customer, :city).all
  end

  def show; end

  def delete; end

  def new; end

  def create; end

  def edit; end

  def update; end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:edit, :update, :destroy]
  before_action :authenticate_admin!


  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_path, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to cities_path, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_path, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def city_params
    params.require(:city).permit(:name)
  end

  def set_city
    @city = City.find(params[:id])
  end
end

app/controllers/cleaners_controller.rb
class CleanersController < ApplicationController
  before_action :set_cleaner, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_admin!, except: [:confirm_token]
  # GET /cleaners
  # GET /cleaners.json
  def index
    @cleaners = Cleaner.all_cleaner
  end

  # GET /cleaners/1
  # GET /cleaners/1.json
  def show
  end

  # GET /cleaners/new
  def new
    @cleaner = Cleaner.new
  end

  # GET /cleaners/1/edit
  def edit
  end

  # POST /cleaners
  # POST /cleaners.json
  def create
    @cleaner = Cleaner.new(cleaner_params)
    @cleaner.confirm_token = SecureRandom.hex(32)
    respond_to do |format|
      if @cleaner.save

        # Use to add all cities of cleaner where he/she work
        add_cities(@cleaner.id)

        UserEmail.confirm_email(@cleaner).deliver_now

        format.html { redirect_to @cleaner, notice: 'Cleaner was successfully created.' }
        format.json { render :show, status: :created, location: @cleaner }
      else
        format.html { render :new }
        format.json { render json: @cleaner.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm_token
    @cleaner = Cleaner.find_by(confirm_token: params[:token])
    if @cleaner
      @cleaner.update!(email_confirmed: true, confirm_token: nil)
      respond_to do |format|
        format.html { redirect_to 'confirm_token', notice: "Confirmation Completed" }
      end
    end
  end

  def confirmed
  end

  def add_cities(cleaner_id)
    city_ids = params[:cleaner][:city_ids]
    city_ids.each do |city|
      CleanersCity.create!(city_id: city, cleaner_id: cleaner_id) unless city.blank?
    end
  end

  # PATCH/PUT /cleaners/1
  # PATCH/PUT /cleaners/1.json
  def update
    respond_to do |format|
      if @cleaner.update(cleaner_params)
        format.html { redirect_to @cleaner, notice: 'Cleaner was successfully updated.' }
        format.json { render :show, status: :ok, location: @cleaner }
      else
        format.html { render :edit }
        format.json { render json: @cleaner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cleaners/1
  # DELETE /cleaners/1.json
  def destroy
    @cleaner.destroy
    respond_to do |format|
      format.html { redirect_to cleaners_url, notice: 'Cleaner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cleaner
      @cleaner = Cleaner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cleaner_params
      params.require(:cleaner).permit(:first_name, :last_name, :quality_score, :city_ids, :email)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(record_for_name)
    "#{record_for_name.first_name} #{record_for_name.last_name}"
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_name_helper.rb
module CityNameHelper
end

app/helpers/cleanercities_helper.rb
module CleanercitiesHelper
end

app/helpers/cleaners_helper.rb
module CleanersHelper
  def verification_state_btn(email_confirmed)
    email_confirmed ? "primary" : "danger"
  end

  def verification_state_msg(email_confirmed)
    email_confirmed ? "Verified" : "Unverified"
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cleaners/_form.html.erb
<div class="form-horizontal">
  <div class="text-center">
    <%= form_for(@cleaner) do |f| %>
      <% if @cleaner.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@cleaner.errors.count, "error") %> prohibited this cleaner from being saved:</h2>

          <ul>
          <% @cleaner.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :Works_in, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= collection_check_boxes(:cleaner, :city_ids, City.Active, :id, :name)  %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.email_field :email, class: "form-control", placeholder: "E-mail Address" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :first_name, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :quality_score, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :quality_score, class: "form-control", placeholder: "Quality Score" %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary"  %>
      </div>
    <% end %>
  </div>
</div>

app/views/cleaners/confirm_token.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li class="active">Cleaner</li>
    <p class="pull-right text-white"><%= link_to "New Cleaner",new_cleaner_path, class: "btn btn-success btn-xs" %></p>
  </ol>

  <div class="jumbotron">
    <p>
      Dear cleaner,<br><br>

      Congratulation...!!! <br><br>

      Now you are part of Homework and soon you get leads from us.<br><br>

      Thank You<br><br>

      Regarding,<br>
      HomeWork
    </p>
  </div>
</div>

app/views/cleaners/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li><%= link_to 'Cleaner', cleaners_path %></li>
    <li class="active"><%= "#{@cleaner.first_name} #{@cleaner.last_name}" %></li>
  </ol>
  <%= render 'form' %>
</div>

app/views/cleaners/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li class="active">Cleaners</li>
    <p class="pull-right text-white"><%= link_to "New Cleaner",new_cleaner_path, class: "btn btn-success btn-xs" %></p>
  </ol>
  <%= render 'layouts/notice' %>

  <div class="table-responsive">
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Confirmation</th>
          <th>Quality score</th>
          <th>Verified</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @cleaners.each_with_index do |cleaner, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= cleaner.first_name %></td>
            <td><%= cleaner.last_name %></td>
            <td><%= cleaner.quality_score %></td>
            <td><%= cleaner.email %></td>
            <td>
              <span class="label label-<%= verification_state_btn(cleaner.email_confirmed) %>">
                <%= verification_state_msg(cleaner.email_confirmed) %>
              </span>
            </td>
            <td><%= link_to 'Show', cleaner %></td>
            <td><%= link_to 'Edit', edit_cleaner_path(cleaner) %></td>
            <td><%= link_to 'Destroy', cleaner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p>
      <strong>Note: </strong>
      No any work is assigned to cleaner, until he/she verifies email.
    </p>
  </div>
</div>

app/views/cleaners/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li><%= link_to "Cleaners", cleaners_path %></li>
    <li class="active">New Cleaner</li>
  </ol>
  <%= render 'layouts/notice' %>
  <%= render 'form' %>
</div>

app/views/cleaners/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li><%= link_to "Cleaners", cleaners_path %></li>
    <li class="active">Cleaner</li>
  </ol>
  <%= render 'layouts/notice' %>
  <div class="jumbotron">
    <p>
      <strong>Email Address:</strong>
      <%= @cleaner.email %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @cleaner.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @cleaner.last_name %>
    </p>

    <p>
      <strong>Quality score:</strong>
      <%= @cleaner.quality_score %>
    </p>

    <p>
      <strong>Email Varification:</strong>
      <%= verification_state_msg(@cleaner.email_confirmed) %>
    </p>

    <p>
      <strong>Work in City(s):</strong><br>
      <div>
        <% @cleaner.cities.each do |city| %>
          <%= "#{city.name}" %><br>
        <% end %>
      </div>
    </p>

    <p>
      <strong>Note: </strong>
      No any work is assigned to cleaner, until he/she verifies email.
    </p>
  </div>
</div>