config/routes.rb
Rails.application.routes.draw do

  root 'customers#new'

  devise_for :admins

  resources :bookings

  resources :cities

  resources :cleaners do
    get 'confirm_token/:token' => 'cleaners#confirm_token', as: 'confirm_email'
  end

  resources :customers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cleaner
  belongs_to :city
  validates_presence_of :cleaner_id, :city_id, message: "Should be selected"
end

app/models/cities_cleaner.rb
class CitiesCleaner < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :cleaners_cities
  has_many :cleaner, through: :cleaners_cities

  enum status: [:Active, :Inactive]

  validates :name, presence: true
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  has_many :connection1s
  has_many :cleaners, :through => :connection1s, :source => :cleaner

end

app/models/cleaner.rb
class Cleaner < ActiveRecord::Base

  has_many :cleaners_cities, dependent: :destroy
  has_many :booking, dependent: :destroy
  has_many :cities, through: :cleaners_cities

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :quality_score, presence: true

  scope :all_cleaner, -> { ( order(id: :desc) ) }
end

app/models/cleaner_city.rb
class CleanerCity < ActiveRecord::Base

  belongs_to :city
  belongs_to :cleaner

end

app/models/cleaners_city.rb
class CleanersCity < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/connection1.rb
class Connection1 < ActiveRecord::Base
  belongs_to :cleaners, :class_name => "Cleaner"
  belongs_to :connection1s, :class_name => "Connection1"

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :booking, dependent: :destroy

  attr_accessor :city_id, :date

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number,presence: true
  validates :city_id, presence: true
  validates :date, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @bookings = Booking.includes(:cleaner, :customer, :city).all
  end

  def show; end

  def delete; end

  def new; end

  def create; end

  def edit; end

  def update; end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:edit, :update, :destroy]
  before_action :authenticate_admin!


  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_path, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to cities_path, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_path, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def city_params
    params.require(:city).permit(:name)
  end

  def set_city
    @city = City.find(params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_admin!, only: [:index]
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit; end

  # POST /customers
  # POST /customers.json
  def create
    respond_to do |format|
      if add_customer
        message = assign_cleaner
        format.html { redirect_to @customer, notice: message }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_customer
    if customer_exist?
      @customer = Customer.find_by(phone_number: params[:customer][:phone_number])
    else
      @customer = Customer.create(customer_params)
    end
  end

  def customer_exist?
    Customer.find_by_phone_number(params[:customer][:phone_number])
  end

  def assign_cleaner
    cleaners = City.find(params[:customer][:city_id]).cleaner.where(email_confirmed: true)
    cleaners.each do |cleaner|
      unless cleaner_available_for_date(cleaner)
        Booking.create(cleaner_id: cleaner.id, customer_id: @customer.id,
                       date: params[:customer][:date])
        # Send email to cleaner for new work assignment
        send_email(cleaner)
        return "Dear Customer, Your home cleaning duty is assign to
          #{cleaner.first_name} #{cleaner.last_name} on the date
          #{params[:customer][:date]}."
      end
    end
    "Dear Customer, Sorry to inform you that because of heavy booking their
      are no any cleaner available in you city for date #{params[:customer][:date]}
      you choose. Please try for another date."
  end

  def cleaner_available_for_date(cleaner)
    Booking.where('cleaner_id = ?', cleaner)
           .where('date = ?', params[:customer][:date]).exists?
  end

  def send_email(cleaner)
    UserEmail.send_lead_to_cleaner(cleaner, @customer,
                                   params[:customer][:date]).deliver
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors,status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :phone_number,
                                     :city_id, :date)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(record_for_name)
    "#{record_for_name.first_name} #{record_for_name.last_name}"
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_name_helper.rb
module CityNameHelper
end

app/helpers/cleanercities_helper.rb
module CleanercitiesHelper
end

app/helpers/cleaners_helper.rb
module CleanersHelper
  def verification_state_btn(email_confirmed)
    email_confirmed ? "primary" : "danger"
  end

  def verification_state_msg(email_confirmed)
    email_confirmed ? "Verified" : "Unverified"
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_admin_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">All Customers</div>
   <div class="panel-body">
     <table border="2" class="table table-hover table-striped">
       <thead>
         <tr>
           <th>Name</th>
           <th>phone_number</th>
           <th>Details</th>
         </tr>
       </thead>
       <tbody>
         <% @customers.each do |customer| %>
           <tr>
             <td><%= full_name(customer) %></td>
             <td><%= customer.phone_number %></td>
             <td>
               <%= link_to "show", customer_path(customer) %>
             </td>
           </tr>
         <% end %>
       </tbody>
     </table>
   </div>
</div>
</div>

app/views/customers/_customer_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Your bookings</div>
  <div class="panel-body">
    <table border="2" class="table table-hover table-striped">
      <tr>
        <th>Date</th>
        <th>Cleaner name</th>
        <th>City</th>
      </tr>
      <% @bookings.each do |booking| %>
        <tr>
          <td>
            <%= booking.datetime %>
          </td>
          <td>
            <%= full_name(booking.cleaner) %>
          </td>
          <td>
            <%= booking.city.city_name %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/customers/_form.html.erb
<div class="form-horizontal">
  <div class="text-center">
  <%= form_for(@customer) do |f| %>
    <% if @customer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

        <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :first_name, class: "col-sm-offset-2 col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :last_name, class: "col-sm-offset-2 col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, class: "col-sm-offset-2 col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone number" %>
      </div>
    </div>

    <div>
      <h3>Schedule you booking</h3>
    </div>

    <div class="form-group">
      <%= f.label :select_city, class: "col-sm-offset-2 col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= collection_select(:customer, :city_id, City.Active, :id, :name, { prompt: "Select your City"}, class: "form-control") %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :select_date, class: "col-sm-offset-2 col-sm-2 control-label" %>
      <div class="col-sm-5">
        <%= f.date_field :date, class: "form-control", placeholder: "Select Date of Job" %>
      </div>
    </div>

    <div>
      <%= f.submit "Send Request", class: "btn btn-primary" %>
    </div>
  <% end %>
  </div>
</div>

app/views/customers/_login.html.erb
<%= form_for(@customer) do |f| %>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li><%= link_to 'Customers', customers_path %></li>
    <li class="active"><%= "#{@customer.first_name} #{@customer.last_name}" %></li>
  </ol>

  <div class="form-horizontal">
    <div class="text-center">
    <%= form_for(@customer) do |f| %>
      <% if @customer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

          <ul>
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :first_name, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :phone_number, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone number" %>
        </div>
      </div>



      <div>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li class="active">Customers</li>
    <p class="pull-right text-white"><%= link_to "New Customer",new_customer_path, class: "btn btn-success btn-xs" %></p>
  </ol>
  <%= render 'layouts/notice' %>


  <div class="table-responsive">
    <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Phone number</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each_with_index do |customer,index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= customer.first_name %></td>
          <td><%= customer.last_name %></td>
          <td><%= customer.phone_number %></td>
          <td><%= link_to 'Show', customer %></td>
          <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
          <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
</div>

app/views/customers/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <% if current_admin %>
      <li><%= link_to "Customers", customers_path %></li>
      <li class="active">Customer Sign Up & Schedule</li>
    <% else %>
      <li class="active">Customer Sign Up & Schedule</li>
    <% end %>
  </ol>
  <%= render 'layouts/notice' %>

  <center><h2>Customer Sign Up & Schedule</h2></center><br>

  <%= render 'form' %>

</div>

app/views/customers/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <% if current_admin %>
      <li><%= link_to "Customers", customers_path %></li>
      <li class="active">Customer Details</li>
    <% else %>
      <li class="active">Customer Details</li>
    <% end %>
  </ol>
  <%= render 'layouts/notice' %>

  <div class="jumbotron">
    <strong><h2>Customer Details</h2></strong><br>

    <p>
      <strong>First name:</strong>
      <%= @customer.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @customer.last_name %>
    </p>

    <p>
      <strong>Phone number:</strong>
      <%= @customer.phone_number %>
    </p>

  </div>
</div>