config/routes.rb
Rails.application.routes.draw do

  root 'customers#new'

  devise_for :admins

  resources :bookings

  resources :cities

  resources :cleaners do
    get 'confirm_token/:token' => 'cleaners#confirm_token', as: 'confirm_email'
  end

  resources :customers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cleaner
  belongs_to :city
  validates_presence_of :cleaner_id, :city_id, message: "Should be selected"
end

app/models/cities_cleaner.rb
class CitiesCleaner < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :cleaners_cities
  has_many :cleaner, through: :cleaners_cities

  enum status: [:Active, :Inactive]

  validates :name, presence: true
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  has_many :connection1s
  has_many :cleaners, :through => :connection1s, :source => :cleaner

end

app/models/cleaner.rb
class Cleaner < ActiveRecord::Base

  has_many :cleaners_cities, dependent: :destroy
  has_many :booking, dependent: :destroy
  has_many :cities, through: :cleaners_cities

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :quality_score, presence: true

  scope :all_cleaner, -> { ( order(id: :desc) ) }
end

app/models/cleaner_city.rb
class CleanerCity < ActiveRecord::Base

  belongs_to :city
  belongs_to :cleaner

end

app/models/cleaners_city.rb
class CleanersCity < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/connection1.rb
class Connection1 < ActiveRecord::Base
  belongs_to :cleaners, :class_name => "Cleaner"
  belongs_to :connection1s, :class_name => "Connection1"

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :booking, dependent: :destroy

  attr_accessor :city_id, :date

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number,presence: true
  validates :city_id, presence: true
  validates :date, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @bookings = Booking.includes(:cleaner, :customer, :city).all
  end

  def show; end

  def delete; end

  def new; end

  def create; end

  def edit; end

  def update; end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:edit, :update, :destroy]
  before_action :authenticate_admin!


  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_path, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to cities_path, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_path, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def city_params
    params.require(:city).permit(:name)
  end

  def set_city
    @city = City.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @customer = Customer.new
    @booking = Booking.new
    @cities = City.all
  end
  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(record_for_name)
    "#{record_for_name.first_name} #{record_for_name.last_name}"
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_name_helper.rb
module CityNameHelper
end

app/helpers/cleanercities_helper.rb
module CleanercitiesHelper
end

app/helpers/cleaners_helper.rb
module CleanersHelper
  def verification_state_btn(email_confirmed)
    email_confirmed ? "primary" : "danger"
  end

  def verification_state_msg(email_confirmed)
    email_confirmed ? "Verified" : "Unverified"
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/_form.html.erb
<div class="form-horizontal">
  <div class="text-center">
    <%= form_for(@city) do |f| %>
      <% if @city.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

          <ul>
          <% @city.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :city_name, class: "col-sm-offset-2 col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :name, class: "form-control", placeholder: "City Name" %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary"  %>
      </div>
    <% end %>
  </div>
</div>

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li><%= link_to "Cities", cities_path %></li>
    <li class="active">Edit <%= @city.name %></li>
  </ol>
  <%= render 'layouts/notice' %>
  <%= render 'form' %>
</div>

app/views/cities/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li class="active">Cities</li>
    <p class="pull-right text-white"><%= link_to "New City",new_city_path, class: "btn btn-success btn-xs" %></p>
  </ol>
  <%= render 'layouts/notice' %>

  <div class="table-responsive">
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>City name</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @cities.each_with_index do |city, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= city.name %></td>
            <td><%= link_to 'Edit', edit_city_path(city) %></td>
            <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cities/new.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "Home Work", root_path %></li>
    <li><%= link_to "Cities", cities_path %></li>
    <li class="active">New City</li>
  </ol>
  <%= render 'layouts/notice' %>
  <%= render 'form' %>
</div>

app/views/cities/show.html.erb
<h2>Details of <%= @city.city_name %></h2>
<div class="panel panel-default">
  <div class="panel-heading">
    Bookings in <%= @city.city_name %>
  </div>
  <div class="panel-body">
    <table border="2"  class="table table-hover table-striped">
      <tr>
        <th>Date</th>
        <th>Customer</th>
        <th>Cleaner</th>
      </tr>
      <% @city.bookings.each do |booking| %>
        <tr>
          <td>
            <%= booking.datetime %>
          </td>
          <td>
            <%= full_name(booking.customer) %>
          </td>
          <td>
            <%= full_name(booking.cleaner) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    Cleaners working in <%= @city.city_name %>
  </div>
  <div class="panel-body">
    <table border="2"  class="table table-hover table-striped">
      <tr>
        <th>Cleaner</th>
        <th>Email</th>
        <th>Quality Score</th>
      </tr>
      <% @city.cleaners.each do |cleaner| %>
        <tr>
          <td>
            <%= full_name(cleaner) %>
          </td>
          <td>
            <%= cleaner.email %>
          </td>
          <td>
            <%= cleaner.quality_score %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>