config/routes.rb
Rails.application.routes.draw do

  root 'customers#new'

  devise_for :admins

  resources :bookings

  resources :cities

  resources :cleaners do
    get 'confirm_token/:token' => 'cleaners#confirm_token', as: 'confirm_email'
  end

  resources :customers

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cleaner
  belongs_to :city
  validates_presence_of :cleaner_id, :city_id, message: "Should be selected"
end

app/models/cities_cleaner.rb
class CitiesCleaner < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :cleaners_cities
  has_many :cleaner, through: :cleaners_cities

  enum status: [:Active, :Inactive]

  validates :name, presence: true
end

app/models/city_name.rb
class CityName < ActiveRecord::Base
  has_many :connection1s
  has_many :cleaners, :through => :connection1s, :source => :cleaner

end

app/models/cleaner.rb
class Cleaner < ActiveRecord::Base

  has_many :cleaners_cities, dependent: :destroy
  has_many :booking, dependent: :destroy
  has_many :cities, through: :cleaners_cities

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :quality_score, presence: true

  scope :all_cleaner, -> { ( order(id: :desc) ) }
end

app/models/cleaner_city.rb
class CleanerCity < ActiveRecord::Base

  belongs_to :city
  belongs_to :cleaner

end

app/models/cleaners_city.rb
class CleanersCity < ActiveRecord::Base
  belongs_to :city
  belongs_to :cleaner
end

app/models/connection1.rb
class Connection1 < ActiveRecord::Base
  belongs_to :cleaners, :class_name => "Cleaner"
  belongs_to :connection1s, :class_name => "Connection1"

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :booking, dependent: :destroy

  attr_accessor :city_id, :date

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number,presence: true
  validates :city_id, presence: true
  validates :date, presence: true
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(record_for_name)
    "#{record_for_name.first_name} #{record_for_name.last_name}"
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_name_helper.rb
module CityNameHelper
end

app/helpers/cleanercities_helper.rb
module CleanercitiesHelper
end

app/helpers/cleaners_helper.rb
module CleanersHelper
  def verification_state_btn(email_confirmed)
    email_confirmed ? "primary" : "danger"
  end

  def verification_state_msg(email_confirmed)
    email_confirmed ? "Verified" : "Unverified"
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-default" %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/_bookings_index.html.erb
<h1>Listing Bookings</h1>
<div class = "table_width">
<% if current_admin.nil? %>
  <div class = "float-right">
  <%= button_to  new_booking_path,method: :get,class: "btn btn-primary",title: 'Add New Booking' do %>
  <span class="glyphicon glyphicon-plus"></span>
  <% end %></div>
<% end %>
<table border = 2 class = "table table-bordered">
  <tr>
    <th> Customer name </th>
    <th> Cleaner name </th>
    <th> City </th>
    <th> Date And Time </th>
  </tr>
<% @bookings.each do |booking|%>
    <tr>
      <td><%= customer_name booking.customer %></td>
      <td><%= cleaner_name booking.cleaner %></td>
      <td><%= booking.city.name %></td>
      <td><%= booking_date booking.datetime %></td>
      <td><%= link_to  booking,title: ' Show Booking' do %>
        <span class="glyphicon glyphicon-eye-open"></span>
        <% end %></td>
    </tr>
<% end %>
</table>
</div>

app/views/admins/create.html.erb
<h1>Admins#create</h1>
<p>Find me in app/views/admins/create.html.erb</p>

app/views/admins/delete.html.erb
<h1>Admins#delete</h1>
<p>Find me in app/views/admins/delete.html.erb</p>

app/views/admins/edit.html.erb
<h1>Admins#edit</h1>
<p>Find me in app/views/admins/edit.html.erb</p>

app/views/admins/index.html.erb
<div class="panel panel-default">
   <div class="panel-heading">All Booking</div>
   <div class="panel-body">
     <table border="2" class="table table-hover table-striped">
        <tr>
          <th>Date</th>
          <th>Customer name</th>
          <th>Customer phone_number</th>
          <th>Cleaner name</th>
          <th>City</th>
        </tr>
        <% @bookings.each do |booking| %>
          <tr>
            <td>
              <%= booking.datetime %>
            </td>
            <td>
              <%= full_name(booking.customer) %>
            </td>
            <td>
              <%= booking.customer.phone_number %>
            </td>
            <td>
              <%= full_name(booking.cleaner) %>
            </td>
            <td>
              <%= booking.city.city_name %>
            </td>
          </tr>
        <% end %>
    </table>
  </div>
</div>

app/views/admins/new.html.erb
<h1>Admins#new</h1>
<p>Find me in app/views/admins/new.html.erb</p>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/show.html.erb
<h1>Admins#show</h1>
<p>Find me in app/views/admins/show.html.erb</p>

app/views/admins/update.html.erb
<h1>Admins#update</h1>
<p>Find me in app/views/admins/update.html.erb</p>

app/views/layouts/_breadcrumbs.html.erb
<ol class="breadcrumb">
  <%- if controller_name == 'bookings' %>
    <li><%= link_to "Home Work", root_path %></li>
    <li class="active">Bookings</li>
  <% end -%>


  <%- if controller_name == 'customers/new' %>
    <li><%= link_to "Home Work", root_path %></li>
    <%- if current_admin %>
      <li><%= link_to "Customers", customers_path %></li>
    <% end -%>
    <li class="active">Customer Sign Up & Schedule</li>
  <% end -%>

  <%- if controller_name == 'customers' %>
  <li><%= link_to "Home Work", root_path %></li>
  <li class="active">Customers</li>
  <p class="pull-right text-white"><%= link_to "New Customer",new_customer_path, class: "btn btn-success btn-xs" %></p>
  <% end -%>

</ol>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home Work", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% if current_admin %>
        <li><%= link_to 'Bookings', bookings_path %></li>
        <li><%= link_to 'Customers', customers_path %></li>
        <li><%= link_to 'Cleaners', cleaners_path %></li>
        <li><%= link_to 'City', cities_path %></li>
      <% else %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if current_admin %>
      <li><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_admin_session_path %></li>
    <% end %>     </ul>
   </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_link.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Home Cleaner</a>
    </div>
    <ul class="nav navbar-nav">
      <% if current_admin %>
        <li><%= link_to 'Cleaners', cleaners_path %></li>
        <li><%= link_to 'Customer', customers_path %></li>
        <li><%= link_to 'Bookings', bookings_path %></li>
        <li><%= link_to 'Cities', cities_path %></li>
        <li><%= link_to 'Logout', destroy_admin_session_path,method: :delete %></li>
      <% else %>
        <% if session[:customer].nil? %>
          <li><%= link_to 'Customer', new_customer_path,method: :get %></li>
          <li><%= link_to 'Admin', new_admin_session_path,method: :get %></li>
        <% else %>
          <li><%= link_to 'Booking', new_booking_path,method: :get %></li>
          <li><%= link_to 'Logout',logout_customer_path, method: :post  %></li>
        <% end %>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert" id="notice"><%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Homework</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar-wrapper">
      <div class="container">
        <%= render 'layouts/nav' %>
      </div>
    </div>

    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/user_email/confirm_email.html.erb
Dear <%= "#{@cleaner.first_name} #{@cleaner.last_name}" %>,

  Congratulation...!!!<br>

  Now you are the part of the <h2>HomeWork</h2> and after confirmation
  of your email address you get leads from us.<br>

  To confirm your account click link below...<br><br>

  <%= link_to "Confirm Email",cleaner_confirm_email_url(@cleaner.id,token: @cleaner.confirm_token)  %>

app/views/user_email/send_lead_to_cleaner.html.erb
Dear <%= "#{@cleaner.first_name} #{@cleaner.last_name}" %>,<br>

  Job Detailss:<br>
    Date Of Job: <%= "#{@dateofjobs}" %><br>
    Customer name : <%= "#{@customer.first_name} #{@customer.last_name}" %><br>
    Contact Number: <%= "#{@customer.phone_number}" %><br>

Regarding,<br>
HomeWork